package ru.mcashesha.kmeans;

import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import ru.mcashesha.metrics.Metric;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests the three KMeans clustering algorithm implementations:
 * {@link LloydKMeans} (classic full-pass iterative),
 * {@link MiniBatchKMeans} (stochastic mini-batch with early stopping), and
 * {@link HierarchicalKMeans} (recursive binary tree via Lloyd at each level).
 *
 * <p>The test suite validates the following aspects for each algorithm:</p>
 * <ul>
 *   <li><b>Correctness</b> -- well-separated synthetic clusters are recovered with 100%
 *       accuracy (each generated point group maps to exactly one distinct cluster).</li>
 *   <li><b>Edge cases</b> -- single cluster (k=1), k equal to the number of data points,
 *       null/empty input data, and k greater than the data size (expected to throw).</li>
 *   <li><b>Loss monotonicity</b> -- more iterations must produce equal or lower loss than fewer.</li>
 *   <li><b>Metric type coverage</b> -- every {@link Metric.Type} (L2, dot product, cosine)
 *       produces valid clustering results.</li>
 *   <li><b>Predict</b> -- fitted models assign unseen test data to valid cluster indices.</li>
 *   <li><b>Cross-algorithm</b> -- all three algorithms produce valid results on the same dataset.</li>
 * </ul>
 *
 * <p>Synthetic data is generated by {@link #generateClusters} which places cluster centers
 * at evenly spaced offsets along every dimension, with a small noise radius to keep clusters
 * well-separated when the {@code spread} parameter is large relative to the noise.</p>
 *
 * <p>A fixed {@link #SEED} ensures reproducibility across runs.</p>
 */
class KMeansTest {

    /** Fixed random seed for deterministic data generation and KMeans initialization. */
    private static final long SEED = 42L;

    /** Dimensionality of test vectors -- kept small for fast test execution. */
    private static final int DIMENSION = 8;

    /**
     * Generates synthetic clustered data with known ground-truth group assignments.
     *
     * <p>Each cluster center is placed at {@code (c * spread, c * spread, ..., c * spread)}
     * for cluster index {@code c}, and each point is offset from its center by uniform
     * noise in [-0.05, 0.05] per dimension. When {@code spread} is large (e.g., 50 or 100),
     * the clusters are perfectly separable.</p>
     *
     * <p>Points are laid out contiguously by cluster: indices
     * {@code [0, pointsPerCluster)} belong to cluster 0,
     * {@code [pointsPerCluster, 2*pointsPerCluster)} to cluster 1, and so on.
     * This ordering is relied upon by {@link #assertHomogeneousClusters}.</p>
     *
     * @param rng              random number generator
     * @param pointsPerCluster number of points in each cluster
     * @param clusterCount     number of clusters to generate
     * @param dimension        dimensionality of each vector
     * @param spread           distance between adjacent cluster centers along each axis
     * @return a flat array of {@code pointsPerCluster * clusterCount} vectors
     */
    private static float[][] generateClusters(Random rng, int pointsPerCluster,
        int clusterCount, int dimension, float spread) {
        float[][] data = new float[pointsPerCluster * clusterCount][dimension];
        for (int c = 0; c < clusterCount; c++) {
            // Place cluster center at (c*spread, c*spread, ..., c*spread)
            float[] center = new float[dimension];
            for (int d = 0; d < dimension; d++)
                center[d] = c * spread;

            // Generate points with small uniform noise around the center
            for (int p = 0; p < pointsPerCluster; p++) {
                int idx = c * pointsPerCluster + p;
                for (int d = 0; d < dimension; d++)
                    data[idx][d] = center[d] + (rng.nextFloat() - 0.5f) * 0.1f;
            }
        }
        return data;
    }

    // ==================== Lloyd KMeans ====================

    /**
     * Verifies that Lloyd KMeans correctly recovers 3 well-separated clusters.
     * With a spread of 100 and noise radius of 0.05, clusters are trivially separable.
     * Each contiguous block of 50 points must be assigned to exactly one unique cluster.
     */
    @Test
    void lloydFit_wellSeparatedClusters_assignsCorrectly() {
        Random rng = new Random(SEED);
        int k = 3;
        int pointsPerCluster = 50;
        float[][] data = generateClusters(rng, pointsPerCluster, k, DIMENSION, 100f);

        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(k).withMaxIterations(100).withRandom(new Random(SEED)).build();

        KMeans.ClusteringResult result = kmeans.fit(data);

        assertValidResult(result, data.length, k);
        // Every point group (as defined by generateClusters layout) must map to a single cluster
        assertHomogeneousClusters(result.getClusterAssignments(), pointsPerCluster, k);
    }

    /**
     * Verifies that with k=1, all points are assigned to cluster 0 (the only cluster).
     * This is a degenerate case where the centroid equals the data mean.
     */
    @Test
    void lloydFit_singleCluster_allPointsSameLabel() {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 30, 1, DIMENSION, 0f);

        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(1).withRandom(new Random(SEED)).build();

        KMeans.ClusteringResult result = kmeans.fit(data);

        assertValidResult(result, data.length, 1);
        // All labels must be 0 when there is only one cluster
        for (int label : result.getClusterAssignments())
            assertEquals(0, label);
    }

    /**
     * Verifies the edge case where k equals the number of data points (k=n=5).
     * Each point should ideally become its own cluster centroid.
     * The result must still pass structural validation (correct counts, valid labels).
     */
    @Test
    void lloydFit_clusterCountEqualsDataSize() {
        float[][] data = new float[5][DIMENSION];
        Random rng = new Random(SEED);
        for (float[] row : data)
            for (int d = 0; d < DIMENSION; d++)
                row[d] = rng.nextFloat();

        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(5).withRandom(new Random(SEED)).build();

        KMeans.ClusteringResult result = kmeans.fit(data);

        assertValidResult(result, 5, 5);
    }

    /**
     * Verifies that {@link LloydKMeans#predict} assigns unseen test data to valid cluster
     * indices in the range [0, k). Test data is generated from the same cluster layout but
     * with a different random seed, simulating previously unseen vectors.
     */
    @Test
    void lloydPredict_assignsToNearestCentroid() {
        Random rng = new Random(SEED);
        int k = 3;
        float[][] trainData = generateClusters(rng, 50, k, DIMENSION, 100f);

        LloydKMeans kmeans = new LloydKMeans(k, Metric.Type.L2SQ_DISTANCE,
            Metric.Engine.SCALAR, 100, 1e-4f, new Random(SEED));

        LloydKMeans.Result model = kmeans.fit(trainData);
        float[][] testData = generateClusters(new Random(123), 10, k, DIMENSION, 100f);
        int[] predicted = kmeans.predict(testData, model);

        // Predicted array length must match the number of test vectors
        assertEquals(testData.length, predicted.length);
        // All predicted labels must be valid cluster indices
        for (int label : predicted)
            assertTrue(label >= 0 && label < k);
    }

    /**
     * Verifies the loss monotonicity property: running Lloyd KMeans for 100 iterations
     * must produce a loss that is less than or equal to the loss after just 1 iteration.
     * This validates that the iterative refinement converges rather than diverges.
     */
    @Test
    void lloydFit_lossDecreases() {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 100, 4, DIMENSION, 10f);

        // Fit with only 1 iteration (essentially just KMeans++ initialization + one reassignment)
        KMeans.ClusteringResult r1 = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(4).withMaxIterations(1).withRandom(new Random(SEED)).build().fit(data);

        // Fit with 100 iterations (should converge to a lower or equal loss)
        KMeans.ClusteringResult r100 = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(4).withMaxIterations(100).withRandom(new Random(SEED)).build().fit(data);

        assertTrue(r100.getLoss() <= r1.getLoss(),
            "Loss after 100 iterations (" + r100.getLoss() + ") should be <= loss after 1 (" + r1.getLoss() + ")");
    }

    /**
     * Verifies that Lloyd KMeans produces valid results for every {@link Metric.Type}
     * (L2 squared distance, dot product, and cosine distance). This ensures that the
     * algorithm does not silently break when switching distance metrics.
     *
     * @param metricType the distance metric to use for clustering
     */
    @ParameterizedTest
    @EnumSource(Metric.Type.class)
    void lloydFit_allMetricTypes(Metric.Type metricType) {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 30, 3, DIMENSION, 50f);

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.LLOYD, metricType, Metric.Engine.SCALAR
        ).withClusterCount(3).withMaxIterations(50).withRandom(new Random(SEED)).build().fit(data);

        assertValidResult(result, data.length, 3);
    }

    /**
     * Verifies that requesting more clusters than data points throws an
     * {@link IllegalArgumentException}. KMeans++ initialization cannot select
     * more initial centroids than there are unique data points.
     */
    @Test
    void lloydFit_clusterCountGreaterThanData_throws() {
        float[][] data = new float[3][DIMENSION];

        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(10).withRandom(new Random(SEED)).build();

        assertThrows(IllegalArgumentException.class, () -> kmeans.fit(data));
    }

    /**
     * Verifies that passing {@code null} as input data throws an
     * {@link IllegalArgumentException} rather than a NullPointerException.
     */
    @Test
    void lloydFit_nullData_throws() {
        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(2).build();

        assertThrows(IllegalArgumentException.class, () -> kmeans.fit(null));
    }

    /**
     * Verifies that passing an empty data array throws an {@link IllegalArgumentException}.
     */
    @Test
    void lloydFit_emptyData_throws() {
        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(2).build();

        assertThrows(IllegalArgumentException.class, () -> kmeans.fit(new float[0][]));
    }

    // ==================== MiniBatch KMeans ====================

    /**
     * Verifies that MiniBatch KMeans correctly recovers 3 well-separated clusters.
     * Despite using stochastic mini-batches (batch size 32), the large cluster separation
     * (spread=100) guarantees correct assignment.
     */
    @Test
    void miniBatchFit_wellSeparatedClusters_assignsCorrectly() {
        Random rng = new Random(SEED);
        int k = 3;
        int pointsPerCluster = 50;
        float[][] data = generateClusters(rng, pointsPerCluster, k, DIMENSION, 100f);

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.MINI_BATCH, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(k).withBatchSize(32).withMaxIterations(200)
            .withRandom(new Random(SEED)).build().fit(data);

        assertValidResult(result, data.length, k);
        assertHomogeneousClusters(result.getClusterAssignments(), pointsPerCluster, k);
    }

    /**
     * Verifies that MiniBatch KMeans handles the degenerate k=1 case, where all points
     * must be assigned to the single cluster.
     */
    @Test
    void miniBatchFit_singleCluster() {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 30, 1, DIMENSION, 0f);

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.MINI_BATCH, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(1).withBatchSize(16).withRandom(new Random(SEED)).build().fit(data);

        assertValidResult(result, data.length, 1);
    }

    /**
     * Verifies that MiniBatch KMeans works correctly when the batch size exceeds the total
     * dataset size. In this case each mini-batch iteration effectively becomes a full-pass
     * Lloyd iteration, which should still produce valid results.
     */
    @Test
    void miniBatchFit_batchSizeLargerThanData() {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 10, 2, DIMENSION, 50f);

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.MINI_BATCH, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(2).withBatchSize(1000).withMaxIterations(50)
            .withRandom(new Random(SEED)).build().fit(data);

        assertValidResult(result, data.length, 2);
    }

    /**
     * Verifies that {@link MiniBatchKMeans#predict} assigns unseen test data to valid
     * cluster indices in the range [0, k). Uses a separate random seed for test data
     * generation to simulate novel inputs.
     */
    @Test
    void miniBatchPredict() {
        Random rng = new Random(SEED);
        int k = 3;
        float[][] trainData = generateClusters(rng, 50, k, DIMENSION, 100f);

        MiniBatchKMeans kmeans = new MiniBatchKMeans(k, 32,
            Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR, 200, 1e-4f, 50, new Random(SEED));

        MiniBatchKMeans.Result model = kmeans.fit(trainData);
        float[][] testData = generateClusters(new Random(123), 10, k, DIMENSION, 100f);
        int[] predicted = kmeans.predict(testData, model);

        assertEquals(testData.length, predicted.length);
        for (int label : predicted)
            assertTrue(label >= 0 && label < k);
    }

    /**
     * Verifies that MiniBatch KMeans early stopping works correctly. With a very high
     * maxIterations (10000) but a tight tolerance and low maxNoImprovementIterations (5),
     * the algorithm should converge and stop early without timing out.
     */
    @Test
    void miniBatchFit_earlyStop() {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 50, 2, DIMENSION, 100f);

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.MINI_BATCH, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(2).withBatchSize(64).withMaxIterations(10000)
            .withMaxNoImprovementIterations(5).withTolerance(1e-6f)
            .withRandom(new Random(SEED)).build().fit(data);

        assertValidResult(result, data.length, 2);
    }

    /**
     * Verifies internal consistency between the cluster sizes reported by
     * {@link KMeans.ClusteringResult#getClusterSizes()} and the sizes recomputed by
     * counting assignments from {@link KMeans.ClusteringResult#getClusterAssignments()}.
     * This catches bugs where the final full-reassignment pass does not correctly
     * update the size metadata.
     */
    @Test
    void miniBatchFit_clusterSizesConsistentWithAssignments() {
        Random rng = new Random(SEED);
        int k = 3;
        float[][] data = generateClusters(rng, 50, k, DIMENSION, 100f);

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.MINI_BATCH, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(k).withBatchSize(32).withMaxIterations(200)
            .withRandom(new Random(SEED)).build().fit(data);

        int[] assignments = result.getClusterAssignments();
        int[] sizes = result.getClusterSizes();

        // Recompute cluster sizes from the raw assignment array
        int[] recomputedSizes = new int[k];
        for (int label : assignments)
            recomputedSizes[label]++;

        // Each cluster's reported size must match the count derived from assignments
        for (int c = 0; c < k; c++)
            assertEquals(recomputedSizes[c], sizes[c],
                "clusterSizes[" + c + "] inconsistent with assignments");
    }

    // ==================== Hierarchical KMeans ====================

    /**
     * Verifies that Hierarchical KMeans produces valid clustering for 4 well-separated groups.
     * The algorithm recursively splits the data with a branch factor of 2 and max depth 4,
     * so the number of leaf clusters depends on the data distribution and stopping criteria.
     */
    @Test
    void hierarchicalFit_wellSeparatedClusters() {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 50, 4, DIMENSION, 100f);

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.HIERARCHICAL, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withBranchFactor(2).withMaxDepth(4).withMaxIterationsPerLevel(30)
            .withRandom(new Random(SEED)).build().fit(data);

        assertNotNull(result.getCentroids());
        assertTrue(result.getCentroids().length > 0);
        // Use the actual leaf count as expectedClusters since hierarchical determines it dynamically
        assertValidResult(result, data.length, result.getCentroids().length);
    }

    /**
     * Verifies that when the dataset is smaller than the minimum cluster size threshold,
     * the entire dataset becomes a single leaf node with exactly 1 centroid.
     * Here, 3 data points with minClusterSize=10 should prevent any recursive splitting.
     */
    @Test
    void hierarchicalFit_smallData_becomesLeaf() {
        float[][] data = new float[3][DIMENSION];
        Random rng = new Random(SEED);
        for (float[] row : data)
            for (int d = 0; d < DIMENSION; d++)
                row[d] = rng.nextFloat();

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.HIERARCHICAL, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withBranchFactor(2).withMaxDepth(4).withMinClusterSize(10)
            .withRandom(new Random(SEED)).build().fit(data);

        // Data size (3) < minClusterSize (10) so no splitting should occur
        assertEquals(1, result.getCentroids().length);
        assertValidResult(result, data.length, 1);
    }

    /**
     * Verifies that {@link HierarchicalKMeans#predict} assigns unseen test data to valid
     * leaf cluster indices. The number of valid indices equals the number of leaf centroids,
     * which is determined dynamically during the hierarchical fit.
     */
    @Test
    void hierarchicalPredict() {
        Random rng = new Random(SEED);
        float[][] trainData = generateClusters(rng, 50, 4, DIMENSION, 100f);

        HierarchicalKMeans kmeans = new HierarchicalKMeans(2, 4, 4, 30, 1e-4f,
            new Random(SEED), Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR);

        HierarchicalKMeans.Result model = kmeans.fit(trainData);
        float[][] testData = generateClusters(new Random(123), 10, 4, DIMENSION, 100f);
        int[] predicted = kmeans.predict(testData, model);

        int leafCount = model.getCentroids().length;
        assertEquals(testData.length, predicted.length);
        // All predicted labels must fall within the valid leaf cluster range
        for (int label : predicted)
            assertTrue(label >= 0 && label < leafCount);
    }

    /**
     * Verifies that with maxDepth=2 and branchFactor=2, only a single binary split occurs,
     * producing at least 2 leaf clusters. This tests the shallowest non-trivial tree depth.
     */
    @Test
    void hierarchicalFit_depthOne_singleSplit() {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 30, 2, DIMENSION, 100f);

        HierarchicalKMeans kmeans = new HierarchicalKMeans(2, 2, 2, 30, 1e-4f,
            new Random(SEED), Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR);

        HierarchicalKMeans.Result result = kmeans.fit(data);

        // With branchFactor=2 and 2 well-separated groups, at least 2 leaves are expected
        assertTrue(result.getCentroids().length >= 2);
        assertValidResult(result, data.length, result.getCentroids().length);
    }

    /**
     * Verifies that Hierarchical KMeans produces valid results for every {@link Metric.Type}.
     * The algorithm's recursive splitting must work correctly regardless of the distance metric.
     *
     * @param metricType the distance metric to use for hierarchical clustering
     */
    @ParameterizedTest
    @EnumSource(Metric.Type.class)
    void hierarchicalFit_allMetricTypes(Metric.Type metricType) {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 30, 2, DIMENSION, 50f);

        KMeans.ClusteringResult result = KMeans.newBuilder(
            KMeans.Type.HIERARCHICAL, metricType, Metric.Engine.SCALAR
        ).withBranchFactor(2).withMaxDepth(3).withMaxIterationsPerLevel(30)
            .withRandom(new Random(SEED)).build().fit(data);

        assertValidResult(result, data.length, result.getCentroids().length);
    }

    // ==================== Cross-algorithm ====================

    /**
     * Verifies that all three KMeans algorithm types (Lloyd, MiniBatch, Hierarchical) produce
     * structurally valid clustering results on the same input dataset. Each algorithm is
     * configured with appropriate parameters for its type and validated for non-null centroids,
     * correct assignment counts, valid label ranges, and non-negative loss.
     */
    @Test
    void allAlgorithms_sameData_produceValidResults() {
        Random rng = new Random(SEED);
        int k = 4;
        float[][] data = generateClusters(rng, 40, k, DIMENSION, 50f);

        for (KMeans.Type type : KMeans.Type.values()) {
            KMeans.Builder builder = KMeans.newBuilder(type, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR)
                .withRandom(new Random(SEED));

            // Configure algorithm-specific parameters
            switch (type) {
                case LLOYD:
                    builder.withClusterCount(k).withMaxIterations(100);
                    break;
                case MINI_BATCH:
                    builder.withClusterCount(k).withBatchSize(32).withMaxIterations(200);
                    break;
                case HIERARCHICAL:
                    builder.withBranchFactor(2).withMaxDepth(4).withMaxIterationsPerLevel(30);
                    break;
            }

            KMeans.ClusteringResult result = builder.build().fit(data);

            assertNotNull(result.getCentroids(), type + ": centroids null");
            assertTrue(result.getCentroids().length > 0, type + ": no centroids");
            assertValidResult(result, data.length, result.getCentroids().length);
            assertTrue(result.getLoss() >= 0, type + ": negative loss");
        }
    }

    // ==================== Helpers ====================

    /**
     * Asserts that a {@link KMeans.ClusteringResult} is structurally valid:
     * <ul>
     *   <li>Result and its fields are non-null.</li>
     *   <li>Number of centroids matches {@code expectedClusters}.</li>
     *   <li>Assignment array length matches {@code expectedSamples}.</li>
     *   <li>All cluster labels are in the valid range [0, expectedClusters).</li>
     *   <li>Cluster sizes array length matches {@code expectedClusters}.</li>
     *   <li>Sum of all cluster sizes equals {@code expectedSamples}.</li>
     *   <li>Loss is a finite number (not NaN or Infinity).</li>
     * </ul>
     *
     * @param result           the clustering result to validate
     * @param expectedSamples  the expected number of data points (assignment array length)
     * @param expectedClusters the expected number of clusters (centroids array length)
     */
    private void assertValidResult(KMeans.ClusteringResult result, int expectedSamples, int expectedClusters) {
        assertNotNull(result);

        float[][] centroids = result.getCentroids();
        assertNotNull(centroids);
        assertEquals(expectedClusters, centroids.length);

        int[] assignments = result.getClusterAssignments();
        assertNotNull(assignments);
        assertEquals(expectedSamples, assignments.length);

        // Every label must be a valid cluster index
        for (int label : assignments)
            assertTrue(label >= 0 && label < expectedClusters,
                "Label " + label + " out of range [0, " + expectedClusters + ")");

        int[] sizes = result.getClusterSizes();
        assertNotNull(sizes);
        assertEquals(expectedClusters, sizes.length);

        // Sum of cluster sizes must equal the total number of samples
        int totalSize = 0;
        for (int s : sizes) {
            assertTrue(s >= 0);
            totalSize += s;
        }
        assertEquals(expectedSamples, totalSize);

        assertTrue(Float.isFinite(result.getLoss()), "Loss should be finite, got " + result.getLoss());
    }

    /**
     * Asserts that each contiguous group of {@code pointsPerCluster} points in the assignment
     * array maps to exactly one cluster, and that each group maps to a distinct cluster.
     *
     * <p>This relies on the data layout produced by {@link #generateClusters}: points
     * {@code [g*pointsPerCluster, (g+1)*pointsPerCluster)} all belong to ground-truth
     * group {@code g}. A correct clustering must assign all points in group {@code g} to
     * the same cluster label, and no two groups may share the same label.</p>
     *
     * @param assignments     the cluster assignment array from the clustering result
     * @param pointsPerCluster number of points in each ground-truth group
     * @param k               number of ground-truth groups (and expected distinct clusters)
     */
    private void assertHomogeneousClusters(int[] assignments, int pointsPerCluster, int k) {
        // Collect the set of unique labels assigned to each ground-truth group
        Set<Integer>[] labelsPerGroup = new HashSet[k];
        for (int g = 0; g < k; g++)
            labelsPerGroup[g] = new HashSet<>();

        for (int i = 0; i < assignments.length; i++) {
            int group = i / pointsPerCluster;
            labelsPerGroup[group].add(assignments[i]);
        }

        // Each group must be assigned to exactly one cluster (homogeneity check)
        for (int g = 0; g < k; g++) {
            assertEquals(1, labelsPerGroup[g].size(),
                "Group " + g + " should map to exactly one cluster, got " + labelsPerGroup[g]);
        }

        // All groups must map to distinct clusters (completeness check)
        Set<Integer> allLabels = new HashSet<>();
        for (int g = 0; g < k; g++)
            allLabels.addAll(labelsPerGroup[g]);
        assertEquals(k, allLabels.size(), "Each group should map to a distinct cluster");
    }
}
