package ru.mcashesha.ivf;

import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import ru.mcashesha.kmeans.KMeans;
import ru.mcashesha.metrics.Metric;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests the {@link IVFIndexFlat} implementation of the Inverted File (IVF) index for
 * approximate nearest neighbor search.
 *
 * <p>The test suite validates the following aspects:</p>
 * <ul>
 *   <li><b>Build properties</b> -- after building, the index reports correct dimension,
 *       cluster count, metric type, and metric engine.</li>
 *   <li><b>Search correctness</b> -- results contain the expected number of items, are
 *       sorted by ascending distance, have unique IDs, and non-negative distances.</li>
 *   <li><b>Edge cases</b> -- topK larger than the dataset, nProbe larger than the number
 *       of clusters, nProbe=1 (single cluster scan), wrong query dimension, and attempting
 *       to search before building the index.</li>
 *   <li><b>Exact match</b> -- querying with a vector identical to a data point returns that
 *       point's ID with distance approximately zero.</li>
 *   <li><b>Full scan equivalence</b> -- when nProbe equals the total cluster count (scanning
 *       all clusters), the IVF index results must match a brute-force linear scan ordering.</li>
 *   <li><b>Custom IDs</b> -- user-provided integer IDs are preserved through the build/search
 *       pipeline and appear correctly in search results.</li>
 *   <li><b>KMeans type coverage</b> -- all three clustering algorithms (Lloyd, MiniBatch,
 *       Hierarchical) produce indexes that support valid search.</li>
 *   <li><b>Metric type coverage</b> -- all distance metrics (L2, dot product, cosine)
 *       produce non-empty, correctly bounded search results.</li>
 * </ul>
 *
 * <p>Synthetic data is generated by {@link #generateClusters} using well-separated cluster
 * centers along each dimension, ensuring deterministic and predictable results.</p>
 *
 * <p>A fixed {@link #SEED} ensures reproducibility across runs.</p>
 */
class IVFIndexFlatTest {

    /** Fixed random seed for deterministic data generation and KMeans initialization. */
    private static final long SEED = 42L;

    /** Dimensionality of test vectors -- kept small for fast test execution. */
    private static final int DIMENSION = 8;

    /**
     * Generates synthetic clustered data with well-separated centers.
     *
     * <p>Cluster centers are placed at {@code (c * spread, c * spread, ..., c * spread)}
     * for cluster index {@code c}, and each point is offset by uniform noise in [-0.05, 0.05]
     * per dimension. Uses the class-level {@link #DIMENSION}.</p>
     *
     * @param rng              random number generator
     * @param pointsPerCluster number of points in each cluster
     * @param clusterCount     number of clusters to generate
     * @param spread           distance between adjacent cluster centers along each axis
     * @return a flat array of {@code pointsPerCluster * clusterCount} vectors
     */
    private static float[][] generateClusters(Random rng, int pointsPerCluster,
        int clusterCount, float spread) {
        float[][] data = new float[pointsPerCluster * clusterCount][DIMENSION];
        for (int c = 0; c < clusterCount; c++) {
            // Place cluster center at (c*spread, c*spread, ..., c*spread)
            float[] center = new float[DIMENSION];
            for (int d = 0; d < DIMENSION; d++)
                center[d] = c * spread;

            // Generate points with small uniform noise around the center
            for (int p = 0; p < pointsPerCluster; p++) {
                int idx = c * pointsPerCluster + p;
                for (int d = 0; d < DIMENSION; d++)
                    data[idx][d] = center[d] + (rng.nextFloat() - 0.5f) * 0.1f;
            }
        }
        return data;
    }

    /**
     * Convenience method that builds an {@link IVFIndexFlat} using Lloyd KMeans with the
     * specified cluster count and metric type. Uses fixed seed and 50 max iterations.
     *
     * @param data         the vectors to index
     * @param clusterCount number of IVF clusters (partitions)
     * @param metricType   the distance metric for both clustering and search
     * @return a fully built IVF index ready for search
     */
    private IVFIndex buildIndex(float[][] data, int clusterCount, Metric.Type metricType) {
        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, metricType, Metric.Engine.SCALAR
        ).withClusterCount(clusterCount).withMaxIterations(50).withRandom(new Random(SEED)).build();

        IVFIndex index = new IVFIndexFlat(kmeans);
        index.build(data);
        return index;
    }

    /**
     * Verifies that after building the index, the reported properties (dimension, cluster count,
     * metric type, and metric engine) match the configuration used during construction.
     */
    @Test
    void build_setsProperties() {
        float[][] data = generateClusters(new Random(SEED), 30, 3, 50f);
        IVFIndex index = buildIndex(data, 3, Metric.Type.L2SQ_DISTANCE);

        assertEquals(DIMENSION, index.getDimension());
        assertEquals(3, index.getCountClusters());
        assertEquals(Metric.Type.L2SQ_DISTANCE, index.getMetricType());
        assertEquals(Metric.Engine.SCALAR, index.getMetricEngine());
    }

    /**
     * Verifies that searching with topK=5 and nProbe=3 (all clusters) returns exactly
     * 5 results when the dataset is large enough (150 vectors).
     */
    @Test
    void search_returnsCorrectTopK() {
        float[][] data = generateClusters(new Random(SEED), 50, 3, 100f);
        IVFIndex index = buildIndex(data, 3, Metric.Type.L2SQ_DISTANCE);

        float[] query = data[0];
        List<IVFIndex.SearchResult> results = index.search(query, 5, 3);

        assertEquals(5, results.size());
    }

    /**
     * Verifies that search results are returned in ascending order of distance.
     * The IVF index uses a max-heap internally and must sort the output before returning.
     */
    @Test
    void search_resultsSortedByDistance() {
        float[][] data = generateClusters(new Random(SEED), 50, 3, 100f);
        IVFIndex index = buildIndex(data, 3, Metric.Type.L2SQ_DISTANCE);

        float[] query = data[0];
        List<IVFIndex.SearchResult> results = index.search(query, 10, 3);

        // Each result's distance must be >= the previous result's distance
        for (int i = 1; i < results.size(); i++) {
            assertTrue(results.get(i).distance >= results.get(i - 1).distance,
                "Results not sorted at position " + i + ": " +
                    results.get(i - 1).distance + " > " + results.get(i).distance);
        }
    }

    /**
     * Verifies that when topK exceeds the total dataset size, the search returns all
     * available data points (10 total = 5 points x 2 clusters) rather than failing.
     */
    @Test
    void search_topKLargerThanData() {
        float[][] data = generateClusters(new Random(SEED), 5, 2, 50f);
        IVFIndex index = buildIndex(data, 2, Metric.Type.L2SQ_DISTANCE);

        // Request 100 results from a dataset of only 10 vectors
        List<IVFIndex.SearchResult> results = index.search(data[0], 100, 2);

        // Should return all 10 vectors (5 per cluster x 2 clusters)
        assertEquals(10, results.size());
    }

    /**
     * Verifies that results are correctly sorted even when topK exceeds the dataset size,
     * exercising the heap's behavior when it cannot fill to capacity.
     */
    @Test
    void search_topKLargerThanData_sortedCorrectly() {
        float[][] data = generateClusters(new Random(SEED), 5, 2, 50f);
        IVFIndex index = buildIndex(data, 2, Metric.Type.L2SQ_DISTANCE);

        List<IVFIndex.SearchResult> results = index.search(data[0], 100, 2);

        for (int i = 1; i < results.size(); i++) {
            assertTrue(results.get(i).distance >= results.get(i - 1).distance,
                "Results not sorted when heapSize < topK at position " + i + ": " +
                    results.get(i - 1).distance + " > " + results.get(i).distance);
        }
    }

    /**
     * Verifies that nProbe values larger than the cluster count are clamped gracefully.
     * The search should probe all available clusters and return the correct number of results.
     */
    @Test
    void search_nProbeLargerThanClusters() {
        float[][] data = generateClusters(new Random(SEED), 30, 3, 50f);
        IVFIndex index = buildIndex(data, 3, Metric.Type.L2SQ_DISTANCE);

        // nProbe=100 exceeds the 3 available clusters; should be clamped internally
        List<IVFIndex.SearchResult> results = index.search(data[0], 5, 100);

        assertEquals(5, results.size());
    }

    /**
     * Verifies that nProbe=1 (probing only the nearest cluster) still returns valid results.
     * The result count may be less than topK if the nearest cluster contains fewer points,
     * but must be at least 1.
     */
    @Test
    void search_nProbeOne_returnsResults() {
        float[][] data = generateClusters(new Random(SEED), 30, 3, 50f);
        IVFIndex index = buildIndex(data, 3, Metric.Type.L2SQ_DISTANCE);

        List<IVFIndex.SearchResult> results = index.search(data[0], 3, 1);

        // With nProbe=1, only the nearest cluster is scanned; result count depends on cluster size
        assertTrue(results.size() >= 1 && results.size() <= 3);
    }

    /**
     * Verifies that querying with an exact copy of data[25] returns ID 25 as the top result
     * with a distance of approximately zero. This confirms that the index correctly identifies
     * exact matches through the cluster assignment and distance computation pipeline.
     */
    @Test
    void search_exactMatchIsFirst() {
        float[][] data = generateClusters(new Random(SEED), 50, 3, 100f);
        IVFIndex index = buildIndex(data, 3, Metric.Type.L2SQ_DISTANCE);

        // Clone to ensure the query is a distinct array (not referencing the indexed data)
        float[] query = data[25].clone();
        List<IVFIndex.SearchResult> results = index.search(query, 1, 3);

        assertEquals(1, results.size());
        // The exact match must have the original sequential ID
        assertEquals(25, results.get(0).id);
        // Distance to self should be zero (within floating-point tolerance)
        assertEquals(0f, results.get(0).distance, 1e-6f);
    }

    /**
     * Verifies that all returned IDs are unique -- no duplicate vectors should appear
     * in the search results.
     */
    @Test
    void search_uniqueIds() {
        float[][] data = generateClusters(new Random(SEED), 30, 3, 50f);
        IVFIndex index = buildIndex(data, 3, Metric.Type.L2SQ_DISTANCE);

        List<IVFIndex.SearchResult> results = index.search(data[0], 20, 3);

        Set<Integer> ids = new HashSet<>();
        for (IVFIndex.SearchResult r : results)
            assertTrue(ids.add(r.id), "Duplicate id: " + r.id);
    }

    /**
     * Verifies that all distances in search results are non-negative.
     * L2 squared distance is always >= 0 by definition.
     */
    @Test
    void search_nonNegativeDistances() {
        float[][] data = generateClusters(new Random(SEED), 30, 3, 50f);
        IVFIndex index = buildIndex(data, 3, Metric.Type.L2SQ_DISTANCE);

        List<IVFIndex.SearchResult> results = index.search(data[0], 10, 3);

        for (IVFIndex.SearchResult r : results)
            assertTrue(r.distance >= 0, "Negative distance: " + r.distance);
    }

    /**
     * Verifies that user-supplied custom IDs (starting at 1000) are preserved through the
     * build/search pipeline. The IVF index reorders data internally by cluster for cache
     * locality, so this test ensures the ID mapping is correctly maintained after reordering.
     */
    @Test
    void build_withCustomIds() {
        float[][] data = generateClusters(new Random(SEED), 20, 2, 50f);
        // Assign custom IDs: 1000, 1001, ..., 1039
        int[] customIds = new int[data.length];
        for (int i = 0; i < customIds.length; i++)
            customIds[i] = 1000 + i;

        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(2).withMaxIterations(50).withRandom(new Random(SEED)).build();

        IVFIndex index = new IVFIndexFlat(kmeans);
        index.build(data, customIds);

        List<IVFIndex.SearchResult> results = index.search(data[0], 5, 2);

        // All returned IDs must fall within the custom range [1000, 1040)
        for (IVFIndex.SearchResult r : results)
            assertTrue(r.id >= 1000 && r.id < 1000 + data.length,
                "Expected custom id range, got " + r.id);
    }

    /**
     * Verifies that attempting to search an index that has not been built yet throws
     * an {@link IllegalStateException}. The index must be explicitly built before any
     * search operation.
     */
    @Test
    void search_beforeBuild_throws() {
        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(2).withRandom(new Random(SEED)).build();

        IVFIndex index = new IVFIndexFlat(kmeans);
        float[] query = new float[DIMENSION];

        assertThrows(IllegalStateException.class, () -> index.search(query, 5, 1));
    }

    /**
     * Verifies that passing {@code null} vectors to build throws an
     * {@link IllegalArgumentException}.
     */
    @Test
    void build_nullVectors_throws() {
        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(2).build();

        IVFIndex index = new IVFIndexFlat(kmeans);

        assertThrows(IllegalArgumentException.class, () -> index.build(null));
    }

    /**
     * Verifies that passing an empty vector array to build throws an
     * {@link IllegalArgumentException}.
     */
    @Test
    void build_emptyVectors_throws() {
        KMeans<? extends KMeans.ClusteringResult> kmeans = KMeans.newBuilder(
            KMeans.Type.LLOYD, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR
        ).withClusterCount(2).build();

        IVFIndex index = new IVFIndexFlat(kmeans);

        assertThrows(IllegalArgumentException.class, () -> index.build(new float[0][]));
    }

    /**
     * Verifies that searching with a query vector whose dimension does not match the index
     * dimension throws an {@link IllegalArgumentException}. The index was built with
     * {@link #DIMENSION}-dimensional vectors, so a query of size DIMENSION+1 must be rejected.
     */
    @Test
    void search_wrongQueryDimension_throws() {
        float[][] data = generateClusters(new Random(SEED), 20, 2, 50f);
        IVFIndex index = buildIndex(data, 2, Metric.Type.L2SQ_DISTANCE);

        // Create a query vector with one extra dimension
        float[] wrongDim = new float[DIMENSION + 1];

        assertThrows(IllegalArgumentException.class, () -> index.search(wrongDim, 5, 1));
    }

    /**
     * Verifies that the IVF index produces non-empty search results for every
     * {@link Metric.Type} (L2 squared distance, dot product, and cosine distance).
     * This ensures the index correctly integrates with all supported distance metrics.
     *
     * @param metricType the distance metric used for both index build and search
     */
    @ParameterizedTest
    @EnumSource(Metric.Type.class)
    void search_allMetricTypes(Metric.Type metricType) {
        float[][] data = generateClusters(new Random(SEED), 30, 3, 50f);
        IVFIndex index = buildIndex(data, 3, metricType);

        List<IVFIndex.SearchResult> results = index.search(data[0], 5, 3);

        assertFalse(results.isEmpty());
        assertTrue(results.size() <= 5);
    }

    /**
     * Verifies that when nProbe equals the total cluster count (full scan), the IVF index
     * produces results identical to a brute-force linear scan. This is the correctness
     * baseline: with all clusters probed, no vectors are missed, so the top-K ordering
     * must exactly match the brute-force ranking.
     */
    @Test
    void search_fullScan_matchesBruteForce() {
        Random rng = new Random(SEED);
        float[][] data = generateClusters(rng, 20, 3, 50f);
        int k = 3;
        IVFIndex index = buildIndex(data, k, Metric.Type.L2SQ_DISTANCE);

        float[] query = data[10];
        // nProbe = k scans all clusters, equivalent to exhaustive search
        List<IVFIndex.SearchResult> results = index.search(query, 5, k);

        // Compute brute-force distances for all data points
        float[] bruteForceDistances = new float[data.length];
        for (int i = 0; i < data.length; i++)
            bruteForceDistances[i] = Metric.Type.L2SQ_DISTANCE.distance(
                Metric.Engine.SCALAR, query, data[i]);

        // Sort indices by ascending brute-force distance
        Integer[] sortedIndices = new Integer[data.length];
        for (int i = 0; i < data.length; i++)
            sortedIndices[i] = i;
        java.util.Arrays.sort(sortedIndices, (a, b) ->
            Float.compare(bruteForceDistances[a], bruteForceDistances[b]));

        // The IVF full-scan results must match the brute-force top-5 ordering exactly
        for (int i = 0; i < results.size(); i++) {
            assertEquals(sortedIndices[i].intValue(), results.get(i).id,
                "Mismatch at position " + i);
        }
    }

    /**
     * Verifies that all three KMeans algorithm types (Lloyd, MiniBatch, Hierarchical) can
     * be used to build a functional IVF index. For each algorithm, the test builds an index,
     * searches it, and validates that results are non-empty, within topK bounds, and sorted
     * by ascending distance.
     */
    @Test
    void search_allKMeansTypes() {
        float[][] data = generateClusters(new Random(SEED), 30, 3, 50f);

        for (KMeans.Type type : KMeans.Type.values()) {
            KMeans.Builder builder = KMeans.newBuilder(type, Metric.Type.L2SQ_DISTANCE, Metric.Engine.SCALAR)
                .withRandom(new Random(SEED));

            // Configure algorithm-specific parameters
            switch (type) {
                case LLOYD:
                    builder.withClusterCount(3).withMaxIterations(50);
                    break;
                case MINI_BATCH:
                    builder.withClusterCount(3).withBatchSize(32).withMaxIterations(100);
                    break;
                case HIERARCHICAL:
                    builder.withBranchFactor(2).withMaxDepth(3).withMaxIterationsPerLevel(30);
                    break;
            }

            IVFIndex index = new IVFIndexFlat(builder.build());
            index.build(data);

            // Use nProbe = total cluster count to ensure all clusters are scanned
            List<IVFIndex.SearchResult> results = index.search(data[0], 5,
                index.getCountClusters());

            assertFalse(results.isEmpty(), type + ": no results");
            assertTrue(results.size() <= 5, type + ": too many results");

            // Verify ascending distance ordering
            for (int i = 1; i < results.size(); i++) {
                assertTrue(results.get(i).distance >= results.get(i - 1).distance,
                    type + ": not sorted at " + i);
            }
        }
    }
}
