/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_mcashesha_metrics_SimSIMD */

#ifndef _Included_ru_mcashesha_metrics_SimSIMD
#define _Included_ru_mcashesha_metrics_SimSIMD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_mcashesha_metrics_SimSIMD
 * Method:    l2DistanceNative
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_ru_mcashesha_metrics_SimSIMD_l2DistanceNative
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     ru_mcashesha_metrics_SimSIMD
 * Method:    dotProductNative
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_ru_mcashesha_metrics_SimSIMD_dotProductNative
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     ru_mcashesha_metrics_SimSIMD
 * Method:    cosineDistanceNative
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_ru_mcashesha_metrics_SimSIMD_cosineDistanceNative
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     ru_mcashesha_metrics_SimSIMD
 * Method:    hammingDistanceB8Native
 * Signature: ([B[B)J
 */
JNIEXPORT jlong JNICALL Java_ru_mcashesha_metrics_SimSIMD_hammingDistanceB8Native
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
