/**
 * @file simsimd_jni.c
 * @brief JNI bridge between Java's {@code ru.mcashesha.metrics.SimSIMD} class
 *        and the SimSIMD C library for hardware-accelerated vector distance
 *        computations.
 *
 * This file implements four native methods declared in the SimSIMD Java class:
 *   - l2Distance      -- squared Euclidean (L2^2) distance between float vectors
 *   - dotProduct      -- inner (dot) product between float vectors
 *   - cosineDistance   -- cosine distance (1 - cosine similarity) between float vectors
 *   - hammingDistanceB8 -- bitwise Hamming distance between byte-packed binary vectors
 *
 * All functions follow the same JNI critical-section pattern for zero-copy
 * array access:
 *
 *   1. Obtain direct pointers to Java heap arrays via
 *      {@code GetPrimitiveArrayCritical}.  Unlike {@code GetFloatArrayElements},
 *      this call may return a direct pointer into the Java heap rather than
 *      allocating a native copy, avoiding an expensive memcpy for large
 *      vectors.
 *
 *   2. While a critical pointer is held the JVM is not allowed to move objects
 *      in memory, which effectively suspends the garbage collector.  Therefore
 *      the window between Get and Release must be kept as short as possible --
 *      only the SimSIMD distance computation sits inside.
 *
 *   3. Arrays are released with the {@code JNI_ABORT} flag, which tells the
 *      JVM "do not copy changes back to the Java array."  This is correct
 *      because all arrays are read-only inputs; no element is modified.
 *
 *   4. Null checks after {@code GetPrimitiveArrayCritical} guard against
 *      allocation failure (the JVM may return NULL if it cannot pin the
 *      array).  On failure any successfully obtained pointer is released
 *      before returning a zero-value sentinel.
 *
 * The JNI header {@code ru_mcashesha_metrics_SimSIMD.h} is auto-generated by
 * {@code javac -h} from the Java class and contains the exact C prototypes
 * that must be implemented here.
 */

#include "ru_mcashesha_metrics_SimSIMD.h"

#include <simsimd/simsimd.h>
#include <math.h>

/* ======================== L2 distance ======================== */

/**
 * Computes the squared Euclidean (L2-squared) distance between two
 * equal-length float vectors.
 *
 * Result = sum_i (a[i] - b[i])^2
 *
 * Returning the squared distance avoids an unnecessary sqrt, which is
 * sufficient for nearest-neighbor comparison (monotonic transformation).
 *
 * @param env   JNI environment pointer (per-thread).
 * @param clazz The {@code SimSIMD} class reference (unused -- static method).
 * @param a     First input vector (float[]).
 * @param b     Second input vector (float[]), must have the same length as a.
 * @return The squared L2 distance, or 0.0f on allocation failure.
 */
JNIEXPORT jfloat JNICALL
Java_ru_mcashesha_metrics_SimSIMD_l2Distance(
    JNIEnv *env,
    jclass clazz,
    jfloatArray a,
    jfloatArray b)
{
    /* Suppress "unused parameter" warning -- static native methods receive
     * jclass (the Class object) rather than a jobject instance.  We do not
     * need it. */
    (void) clazz;

    jsize len = (*env)->GetArrayLength(env, a);

    /* --- Begin critical section: GC is effectively paused here. --- */
    jfloat *ptrA = (*env)->GetPrimitiveArrayCritical(env, a, NULL);
    jfloat *ptrB = (*env)->GetPrimitiveArrayCritical(env, b, NULL);

    /* If either pointer is NULL the JVM could not pin the array.
     * Release whichever was successfully obtained and return a safe default. */
    if (ptrA == NULL || ptrB == NULL)
    {
        if (ptrA != NULL)
        {
            (*env)->ReleasePrimitiveArrayCritical(env, a, ptrA, JNI_ABORT);
        }
        if (ptrB != NULL)
        {
            (*env)->ReleasePrimitiveArrayCritical(env, b, ptrB, JNI_ABORT);
        }
        return 0.0f;
    }

    /* Delegate to SimSIMD's SIMD-optimized L2-squared implementation.
     * The library selects the best instruction set (AVX-512, AVX2, NEON, ...)
     * at runtime. */
    simsimd_distance_t distSq = 0.0;
    simsimd_l2sq_f32(
        (simsimd_f32_t const *) ptrA,
        (simsimd_f32_t const *) ptrB,
        (simsimd_size_t) len,
        &distSq);

    /* Release arrays with JNI_ABORT -- no data was modified, so there is
     * nothing to copy back to the Java heap. */
    (*env)->ReleasePrimitiveArrayCritical(env, a, ptrA, JNI_ABORT);
    (*env)->ReleasePrimitiveArrayCritical(env, b, ptrB, JNI_ABORT);
    /* --- End critical section: GC may resume. --- */

    return (jfloat) distSq;
}

/* ======================== dot product ======================== */

/**
 * Computes the inner (dot) product of two equal-length float vectors.
 *
 * Result = sum_i a[i] * b[i]
 *
 * Note: the Java caller negates the result when using dot product as a
 * distance metric so that "lower is closer" semantics are preserved
 * across all metric types.
 *
 * @param env   JNI environment pointer (per-thread).
 * @param clazz The {@code SimSIMD} class reference (unused -- static method).
 * @param a     First input vector (float[]).
 * @param b     Second input vector (float[]), must have the same length as a.
 * @return The dot product, or 0.0f on allocation failure.
 */
JNIEXPORT jfloat JNICALL
Java_ru_mcashesha_metrics_SimSIMD_dotProduct(
    JNIEnv *env,
    jclass clazz,
    jfloatArray a,
    jfloatArray b)
{
    (void) clazz; /* Unused -- see l2Distance comment. */

    jsize len = (*env)->GetArrayLength(env, a);

    /* --- Begin critical section --- */
    jfloat *ptrA = (*env)->GetPrimitiveArrayCritical(env, a, NULL);
    jfloat *ptrB = (*env)->GetPrimitiveArrayCritical(env, b, NULL);

    if (ptrA == NULL || ptrB == NULL)
    {
        if (ptrA != NULL)
        {
            (*env)->ReleasePrimitiveArrayCritical(env, a, ptrA, JNI_ABORT);
        }
        if (ptrB != NULL)
        {
            (*env)->ReleasePrimitiveArrayCritical(env, b, ptrB, JNI_ABORT);
        }
        return 0.0f;
    }

    /* SimSIMD's dot-product kernel for 32-bit floats. */
    simsimd_distance_t product = 0.0;
    simsimd_dot_f32(
        (simsimd_f32_t const *) ptrA,
        (simsimd_f32_t const *) ptrB,
        (simsimd_size_t) len,
        &product);

    (*env)->ReleasePrimitiveArrayCritical(env, a, ptrA, JNI_ABORT);
    (*env)->ReleasePrimitiveArrayCritical(env, b, ptrB, JNI_ABORT);
    /* --- End critical section --- */

    return (jfloat) product;
}

/* ======================== cosine distance ======================== */

/**
 * Computes the cosine distance between two equal-length float vectors.
 *
 * Result = 1 - (a . b) / (||a|| * ||b||)
 *
 * The result lies in [0, 2]:  0 means identical direction, 1 means
 * orthogonal, 2 means diametrically opposite.
 *
 * @param env   JNI environment pointer (per-thread).
 * @param clazz The {@code SimSIMD} class reference (unused -- static method).
 * @param a     First input vector (float[]).
 * @param b     Second input vector (float[]), must have the same length as a.
 * @return The cosine distance (1 - cosine similarity), or 0.0f on failure.
 */
JNIEXPORT jfloat JNICALL
Java_ru_mcashesha_metrics_SimSIMD_cosineDistance(
    JNIEnv *env,
    jclass clazz,
    jfloatArray a,
    jfloatArray b)
{
    (void) clazz; /* Unused -- see l2Distance comment. */

    jsize len = (*env)->GetArrayLength(env, a);

    /* --- Begin critical section --- */
    jfloat *ptrA = (*env)->GetPrimitiveArrayCritical(env, a, NULL);
    jfloat *ptrB = (*env)->GetPrimitiveArrayCritical(env, b, NULL);

    if (ptrA == NULL || ptrB == NULL)
    {
        if (ptrA != NULL)
        {
            (*env)->ReleasePrimitiveArrayCritical(env, a, ptrA, JNI_ABORT);
        }
        if (ptrB != NULL)
        {
            (*env)->ReleasePrimitiveArrayCritical(env, b, ptrB, JNI_ABORT);
        }
        return 0.0f;
    }

    /* SimSIMD's cosine-distance kernel for 32-bit floats. */
    simsimd_distance_t distance = 0.0;
    simsimd_cos_f32(
        (simsimd_f32_t const *) ptrA,
        (simsimd_f32_t const *) ptrB,
        (simsimd_size_t) len,
        &distance);

    (*env)->ReleasePrimitiveArrayCritical(env, a, ptrA, JNI_ABORT);
    (*env)->ReleasePrimitiveArrayCritical(env, b, ptrB, JNI_ABORT);
    /* --- End critical section --- */

    return (jfloat) distance;
}

/* ======================== hamming B8 ======================== */

/**
 * Computes the bitwise Hamming distance between two equal-length byte arrays.
 *
 * Each byte is treated as 8 independent bits; the result is the total number
 * of bit positions at which the two arrays differ.
 *
 * This is useful for comparing binary-quantized vectors where each dimension
 * has been reduced to a single bit.
 *
 * @param env   JNI environment pointer (per-thread).
 * @param clazz The {@code SimSIMD} class reference (unused -- static method).
 * @param a     First input byte array.
 * @param b     Second input byte array, must have the same length as a.
 * @return The Hamming distance (number of differing bits), or 0 on failure.
 */
JNIEXPORT jlong JNICALL
Java_ru_mcashesha_metrics_SimSIMD_hammingDistanceB8(
    JNIEnv *env,
    jclass clazz,
    jbyteArray a,
    jbyteArray b)
{
    (void) clazz; /* Unused -- see l2Distance comment. */

    jsize len = (*env)->GetArrayLength(env, a);

    /* --- Begin critical section --- */
    jbyte *ptrA = (*env)->GetPrimitiveArrayCritical(env, a, NULL);
    jbyte *ptrB = (*env)->GetPrimitiveArrayCritical(env, b, NULL);

    if (ptrA == NULL || ptrB == NULL)
    {
        if (ptrA != NULL)
        {
            (*env)->ReleasePrimitiveArrayCritical(env, a, ptrA, JNI_ABORT);
        }
        if (ptrB != NULL)
        {
            (*env)->ReleasePrimitiveArrayCritical(env, b, ptrB, JNI_ABORT);
        }
        return 0L;
    }

    /* SimSIMD's Hamming distance kernel for 8-bit packed binary vectors. */
    simsimd_distance_t distance = 0.0;
    simsimd_hamming_b8(
        (simsimd_b8_t const *) ptrA,
        (simsimd_b8_t const *) ptrB,
        (simsimd_size_t) len,
        &distance);

    (*env)->ReleasePrimitiveArrayCritical(env, a, ptrA, JNI_ABORT);
    (*env)->ReleasePrimitiveArrayCritical(env, b, ptrB, JNI_ABORT);
    /* --- End critical section --- */

    return (jlong) distance;
}
